server:
  address: ${SERVER_ADDRESS:0.0.0.0}
  port: ${SERVER_PORT:8080}
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:carekeeperdb}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: ${HIKARI_MAXIMUM_POOL_SIZE:20}
      minimum-idle: ${HIKARI_MINIMUM_IDLE:5}
      idle-timeout: ${HIKARI_IDLE_TIMEOUT:30000}
      max-lifetime: ${HIKARI_MAX_LIFETIME:1800000}
      connection-timeout: ${HIKARI_CONNECTION_TIMEOUT:30000}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL:validate}
    show-sql: ${JPA_SHOW_SQL:false}
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  mail:
    gmail:
      host: ${MAIL_HOST:smtp.gmail.com}
      port: ${MAIL_PORT:587}
      username: ${MAIL_USERNAME:}
      password: ${MAIL_PASSWORD:}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
logging:
  level:
    root: ${LOG_ROOT:INFO}
    com.example.carekeeper: ${LOG_APP:INFO}
    org.hibernate.SQL: ${LOG_HIBERNATE_SQL:WARN}
    org.springframework: ${LOG_SPRING:INFO}
